// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbqijxkmtuaoggocgzdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJicWlqeGttdHVhb2dnb2NnemRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3MDE5NTEsImV4cCI6MjA3MDI3Nzk1MX0.wczuLogZusn8Vy9jPy48j3iP8l_TlEUFB1oLrzhWjpE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});